title: Blake Rogan
tagline: My Personal Blog
description: >-
  A website about what I have learned and maybe you can learn about something

url: 'https://cethric.github.io'
baseurl: ''
permalink: /posts/:title/

author: Blake Rogan
avatar: /assets/img/avatar.png
github:
  username: Cethric

twitter:
  username: twitter_username

linkedIn:
  username: Blake-Rogan

social:
  name: Blake Rogan
  email: blake.rogan@outlook.com
  links:
    # The first element serves as the copyright owner's link
    - https://www.linkedin.com/in/Blake-Rogan
    - https://github.com/Cethric

google_site_verification: qBUuJ4hXK6UG9lutKJhYufwvO3q-Mt4ZyVWCovhfrOU

# http://www.timezoneconverter.com/cgi-bin/findzone/findzone
timezone: Australia/Sydney

google_analytics:
  id: 'UA-61374045-1'
  pv:
    enabled: false
    proxy_url: ''
    proxy_endpoint: ''
    cache: false

disqus:
  comments: false
  shortname: ''    # Fill with your Disqus shortname. › https://help.disqus.com/en/articles/1717111-what-s-a-shortname


theme_mode: dual
toc: true
paginate: 10

markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts: # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: 'highlight'
    # default_lang: console
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1


defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: true
      toc: true
      location: Post
      breadcrumb:
        - label: Posts
          url: /
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: tags
    values:
      tab_active: Tags
      location: Tag
      breadcrumb:
        - label: Home
          url: /
        - label: Tags
          url: /tabs/tags/
  - scope:
      path: categories
    values:
      tab_active: Categories
      location: Category
      breadcrumb:
        - label: Home
          url: /
        - label: Categories
          url: /tabs/categories/
  - scope:
      path: tabs
    values:
      layout: page
      dynamic_title: true    # Hide title in mobile screens.
      breadcrumb:
        - label: Home
          url: /
  - scope:
      path: assets/data
    values:
      layout: compress


sass:
  sass_dir: /assets/css
  style: compressed

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: [html, head, body, dt, dd, rt, rp, optgroup, option, colgroup, caption, thead, tbody, tfoot, tr, td, th]
  profile: false
  blanklines: false
  ignore:
    envs: []

exclude:
  - vendor
  - Gemfile.lock
  - Gemfile
  - tools
  - docs
  - README.md
  - run.sh

sitemap_exclude:
  fuzzy:
    - /assets/
  accurate:
    - /norobots/
    - /tabs/
    - /categories/
    - /tags/
    - /posts/
    - 404.html
    - feed.xml
    - sitemap.xml
    - robots.txt
    - redirects.json

plugins:
  - jekyll-admin

prose:
  rooturl: ''
  siteurl: 'https://cethric.github.io'
  media: 'media'
  ignore:
    - .idea
    - _data
    - _includes
    - _layouts
    - _scripts
    - assets
    - categories
    - tags
    - tools
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
    - run.sh
    - 404.html
    - feed.xml
    - index.html
    - robots.txt
    - sitemap.xml
  metadata:
    _posts:
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "time"
        field:
          element: "text"
          label: "Time"
          value: CURRENT_DATETIME
      - name: "author"
        field:
          element: "text"
          label: "Author"
          value: CURRENT_USER
      - name: "toc"
        field:
          element: "checkbox"
          label: "Show Table of Contents"
          value: true
      - name: "published"
        field:
          element: "checkbox"
          label: "Published"
          value: true
      - name: "excerpt_separator"
        field:
          element: "hidden"
          value: "<!-- content -->"
      - name: "tags"
        field:
          element: "multiselect"
          label: "Tags"
          placeholder: "Tags"
          alterable: true
      - name: "categories"
        field:
          element: "multiselect"
          label: "Categories"
          help: "Only select 2 categories (the parser will only read the first 2 any way"
          placeholder: "Only select 2"
          alterable: true
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
    _drafts:
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "time"
        field:
          element: "text"
          label: "Time"
          value: CURRENT_DATETIME
      - name: "author"
        field:
          element: "text"
          label: "Author"
          value: CURRENT_USER
      - name: "toc"
        field:
          element: "checkbox"
          label: "Show Table of Contents"
          value: true
      - name: "published"
        field:
          element: "checkbox"
          label: "Published"
          value: false
      - name: "excerpt_separator"
        field:
          element: "hidden"
          value: "<!-- content -->"
      - name: "tags"
        field:
          element: "multiselect"
          label: "Tags"
          placeholder: "Tags"
          alterable: true
      - name: "categories"
        field:
          element: "multiselect"
          label: "Categories"
          help: "Only select 2 categories (the parser will only read the first 2 any way"
          placeholder: "Only select 2"
          alterable: true
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
  users:
    - login: "Cethric"
      user: "Blake Rogan"