# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Your awesome title
email: roganBlake@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://Cethric.github.io" # the base hostname & protocol for your site
twitter_username: 
github_username:  Cethric
linkedin_username: blake-rogan-74920a114
omz_forum_username: cethric
facebook_username: blake.rogan.18
lsi: false

# reading
exclude: ['tmp']

# Build settings
markdown: kramdown


sass:
    style: compressed
    sass_dir: "_sass"

# RSS Generator
name: Cethric.github.com
author: Blake Rogan
copyright: © 2016 Blake Rogan
rss_path: /
rss_name: rss.xml
rss_post_limit: -1

# Deploy
deploy:
 - echo 'DEPLOY'

# Plugins
gems:
 - jekyll-coffeescript
 - jekyll-watch
 - jekyll-assets
 - jekyll-deploy
 - jekyll_figure
 - jekyll-email-protect
