# Site settings
title: Cethric.github.io
email: ""
description: > # this means to ignore newlines until "baseurl:"
  Yet to write a description
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://Cethric.github.io.com" # the base hostname & protocol for your site
github_username:  Cethric

# Build settings
markdown: kramdown
